import { NextApiRequest, NextApiResponse, NextPage } from "next";
import { Router } from 'next/router'
import { getLink } from '../lib/db'
import Head from "next/head";

export async function getServerSideProps({params}) {
  const urlSlug = params.slug

  const link = await getLink(urlSlug);

  if (link) {
    return {
      redirect: {
        destination: link.linkUrl,
        permanent: false,
      },
    };
  }

  return {
    props: {},
  };
}

function SlugPage(){
  return (
    <div>
      <Head>
        <title>URL Shortener</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Requested link not found</h1>
    </div>
  );
};

export default SlugPage;