import { getLink } from '../lib/db'
import Head from "next/head";

export async function getServerSideProps({params}) {
  const urlSlug = params.slug
  const link = await getLink(urlSlug);

  if ("details" in link) {
    return {
      notFound: true,
    }
  }else{
      return {
        redirect: {
          destination: link.linkUrl,
          permanent: false,
        },
      };
  }
}

function SlugPage(){
  return (
    <div>
      <Head>
        <title>URL Shortener</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Requested link not found</h1>
    </div>
  );
};

export default SlugPage;